Repository EcoJulia/BiobakeryUtils.jl, pull requests merged in 2021-10, with the labels that each got.

#59 Humann profiles
  Project.toml
  src/BiobakeryUtils.jl
  src/humann.jl
  test/files/humann_joined.tsv
  test/files/humann_single_1.tsv
  test/files/humann_single_2.tsv
  test/runtests.jl
Labels: enhancement

#49 taxfilter & taxfilter! documentation
  src/metaphlan.jl
Labels: docs

#47 adding rm_strat
  src/general.jl
  test/files/humanntestfile.tsv
  test/runtests.jl
Labels: enhancement, docs

#62 remove DataFrames dependency
  Project.toml
  docs/Project.toml
  src/BiobakeryUtils.jl
  src/general.jl
  src/humann.jl
  src/metaphlan.jl
  test/Project.toml
  test/runtests.jl
Labels: enhancement

#63 Metaphlan and Humann tutorials
  .github/workflows/ci.yml
  .gitignore
  Project.toml
  docs/Manifest.toml
  docs/make.jl
  docs/src/conda.md
  docs/src/general.md
  docs/src/gettingstarted.md
  docs/src/humann.md
  docs/src/index.md
  docs/src/metaphlan.md
  docs/src/tutorial.md
  src/BiobakeryUtils.jl
  src/general.jl
  src/humann.jl
  src/metaphlan.jl
  test/runtests.jl
Labels: docs, Complexity: medium

#68 fix docstring for install_deps
  src/BiobakeryUtils.jl
Labels: docs

#69 Metaphlan Tutorials
  .gitignore
  docs/Project.toml
  docs/make.jl
  docs/src/gettingstarted.md
  docs/src/humann.md
  docs/src/img/metaphlan_pcoa.png
  docs/src/img/metaphlan_stack.png
  docs/src/metaphlan.md
  docs/src/microbiome.md
  src/BiobakeryUtils.jl
  src/humann.jl
  src/metaphlan.jl
  src/utils.jl
  test/files/humann/joined.tsv
  test/files/humann/single_1.tsv
  test/files/humann/single_2.tsv
  test/files/humanntestfile.tsv
  test/files/metaphlan/SRS014459-Stool_profile.tsv
  test/files/metaphlan/SRS014464-Anterior_nares_profile.tsv
  test/files/metaphlan/SRS014470-Tongue_dorsum_profile.tsv
  test/files/metaphlan/SRS014472-Buccal_mucosa_profile.tsv
  test/files/metaphlan/SRS014476-Supragingival_plaque_profile.tsv
  test/files/metaphlan/SRS014494-Posterior_fornix_profile.tsv
  test/files/metaphlan_multi_test.tsv
  test/files/metaphlan_multi_test_unidentified.tsv
  test/files/metaphlan_single1.tsv
  test/files/metaphlan_single2.tsv
  test/runtests.jl
Labels: docs

#87 nprocs-> nproc
  src/metaphlan.jl
Labels: docs
